/**
 * Copyright (C) 2020 to the present, Crestron Electronics, Inc.
 * All rights reserved.
 * No part of this software may be reproduced in any form, machine
 * or natural, without the express written consent of Crestron Electronics.
 * Use of this source code is subject to the terms of the Crestron Software License Agreement 
 * under which you licensed this source code.  

 * This code was automatically generated by Crestron's code generation tool.
*/
let pagedisplayModule = (function () {
  "use strict";

  /**
   * Initialize Method
   */
  function onInit() {}

  /**
   * All public or private methods which need to call onInit
   */
  let pagedisplayWidget = document.querySelector("#pagedisplay-import-widget");
  pagedisplayWidget.addEventListener("afterLoad", onInit);

  /**
   * All public method and properties are exported here
   */
  return {  
    
  };

})();
